---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod-reloader.fullname" . }}
  labels:
    {{- include "pod-reloader.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: webhooks
      name: https
  selector:
    {{- include "pod-reloader.selectorLabels" . | nindent 4 }}